# Generated by Django 4.2.3 on 2024-05-08 05:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0002_fin_purchase_order_converted_to_rec_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_delivery_challan',
            name='price_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Finsys_App.fin_price_list'),
        ),
        migrations.AddField(
            model_name='fin_delivery_challan',
            name='price_list_applied',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employee_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 5, 8)),
        ),
        migrations.AlterField(
            model_name='fin_attendance_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 5, 8)),
        ),
        migrations.AlterField(
            model_name='fin_attendance_history',
            name='date',
            field=models.DateField(default=datetime.date(2024, 5, 8)),
        ),
        migrations.AlterField(
            model_name='holiday_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 5, 8)),
        ),
    ]
