# Generated by Django 4.2.3 on 2024-01-12 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0002_fin_cnotification_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fin_Price_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('types', models.CharField(blank=True, choices=[('Sales', 'Sales'), ('Purchase', 'Purchase')], default='Sales', max_length=15, null=True)),
                ('item_rate', models.CharField(blank=True, choices=[('percentage', 'Markup or Markdown the item rates by a percentage'), ('individual_rate', 'Enter the rate individually for each item')], default='percentage', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, default='Indian Rupee', max_length=255, null=True)),
                ('up_or_down', models.CharField(default='None', max_length=100)),
                ('percentage', models.CharField(blank=True, max_length=100, null=True)),
                ('round_off', models.CharField(default='None', max_length=100)),
                ('status', models.CharField(blank=True, default='Active', max_length=15, null=True)),
                ('Company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('Login_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
            ],
        ),
        migrations.CreateModel(
            name='Fin_PriceList_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_rate', models.FloatField(blank=True, default=0.0, null=True)),
                ('custom_rate', models.FloatField(blank=True, default=0.0, null=True)),
                ('Company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('Login_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_items')),
                ('list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_price_list')),
            ],
        ),
    ]
