# Generated by Django 4.2.3 on 2024-04-05 04:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0003_fin_creditnote_fin_creditnote_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fin_Retainer_Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Customer_billing_address', models.CharField(blank=True, max_length=10, null=True)),
                ('Customer_gst_type', models.CharField(blank=True, max_length=10, null=True)),
                ('Customer_gstin', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Customer_place_of_supply', models.CharField(blank=True, max_length=100, null=True)),
                ('Retainer_Invoice_number', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Retainer_Invoice_date', models.DateField(blank=True, null=True)),
                ('Reference_number', models.IntegerField(null=True)),
                ('Payment_Method', models.CharField(blank=True, max_length=10, null=True)),
                ('Cheque_number', models.CharField(blank=True, max_length=100, null=True)),
                ('UPI_number', models.CharField(blank=True, max_length=100, null=True)),
                ('Bank_account_no', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Document', models.FileField(blank=True, upload_to='file/retinv')),
                ('Sub_total', models.FloatField(blank=True, null=True)),
                ('Adjustment', models.FloatField(blank=True, default=0, null=True)),
                ('Grand_total', models.FloatField(blank=True, null=True)),
                ('Paid_amount', models.FloatField(default=0, max_length=100, null=True)),
                ('Balance', models.FloatField(max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Sent', 'Sent')], max_length=150, null=True)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('Customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_customers')),
                ('LoginDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
            ],
        ),
        migrations.AlterField(
            model_name='employee_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 5)),
        ),
        migrations.AlterField(
            model_name='fin_attendance_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 5)),
        ),
        migrations.AlterField(
            model_name='fin_attendance_history',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 5)),
        ),
        migrations.AlterField(
            model_name='holiday_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 5)),
        ),
        migrations.CreateModel(
            name='Fin_Retainer_Invoice_Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reference_no', models.BigIntegerField()),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('LoginDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
            ],
        ),
        migrations.CreateModel(
            name='Fin_Retainer_Invoice_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HSN', models.CharField(max_length=100, null=True)),
                ('Quantity', models.IntegerField(default=0, null=True)),
                ('Price', models.CharField(max_length=100, null=True)),
                ('Discription', models.CharField(max_length=100, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('Total', models.FloatField(max_length=100, null=True)),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('Item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_items')),
                ('LoginDetails', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
                ('Ret_Inv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_retainer_invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Fin_Retainer_Invoice_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('action', models.CharField(blank=True, choices=[('Created', 'Created'), ('Edited', 'Edited')], max_length=20, null=True)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('LoginDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
                ('Ret_Invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_retainer_invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Fin_Retainer_Invoice_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('LoginDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
                ('Ret_Invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_retainer_invoice')),
            ],
        ),
    ]
