# Generated by Django 4.2.3 on 2024-01-05 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0003_fin_chart_of_account_fin_chartofaccount_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fin_chart_of_account',
            old_name='company_id',
            new_name='Company',
        ),
        migrations.RenameField(
            model_name='fin_chart_of_account',
            old_name='Login_Id',
            new_name='LoginDetails',
        ),
        migrations.RenameField(
            model_name='fin_chartofaccount_history',
            old_name='company_id',
            new_name='Company',
        ),
        migrations.RenameField(
            model_name='fin_chartofaccount_history',
            old_name='Login_Id',
            new_name='LoginDetails',
        ),
        migrations.RenameField(
            model_name='fin_items',
            old_name='company_id',
            new_name='Company',
        ),
        migrations.RenameField(
            model_name='fin_items',
            old_name='Login_Id',
            new_name='LoginDetails',
        ),
        migrations.RenameField(
            model_name='fin_items_transaction_history',
            old_name='company_id',
            new_name='Company',
        ),
        migrations.RenameField(
            model_name='fin_items_transaction_history',
            old_name='Login_Id',
            new_name='LoginDetails',
        ),
        migrations.RenameField(
            model_name='fin_units',
            old_name='company_id',
            new_name='Company',
        ),
        migrations.RenameField(
            model_name='fin_units',
            old_name='name',
            new_name='LoginDetails',
        ),
    ]
