# Generated by Django 4.2.3 on 2024-01-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0004_rename_company_id_fin_price_list_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_price_list',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
