# Generated by Django 4.2.3 on 2024-01-05 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0004_rename_company_id_fin_chart_of_account_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fin_units',
            old_name='LoginDetails',
            new_name='name',
        ),
    ]
