# Generated by Django 4.2.3 on 2024-05-08 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0004_fin_sales_order_price_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_purchase_order',
            name='price_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Finsys_App.fin_price_list'),
        ),
        migrations.AddField(
            model_name='fin_purchase_order',
            name='price_list_applied',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
