# Generated by Django 4.2.3 on 2024-01-12 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0005_fin_price_list_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fin_price_list',
            old_name='types',
            new_name='type',
        ),
    ]
