# Generated by Django 4.2.3 on 2024-04-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0005_alter_employee_comment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_expense',
            name='amount_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
