# Generated by Django 4.2.3 on 2024-01-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0006_fin_cnotification_vendors'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_invoice',
            name='price_list_applied',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
