# Generated by Django 4.2.3 on 2024-04-08 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0006_fin_expense_amount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_chartofaccount_transactions',
            name='expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_expense'),
        ),
    ]
