# Generated by Django 4.2.3 on 2024-01-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0007_fin_pricelist_transaction_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fin_price_list',
            name='round_off',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
    ]
