# Generated by Django 4.2.3 on 2024-02-02 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0008_fin_sales_order_fin_sales_order_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fin_sales_order_items',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='fin_sales_order_items',
            name='LoginDetails',
        ),
    ]
