# Generated by Django 4.2.3 on 2024-04-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0008_remove_fin_creditnote_reference_creditnote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fin_creditnote_reference',
            name='reference_number',
            field=models.BigIntegerField(blank=True, max_length=150, null=True),
        ),
    ]
