# Generated by Django 4.2.3 on 2024-04-17 09:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0009_alter_fin_creditnote_reference_reference_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fin_creditnote',
            name='price',
        ),
        migrations.AddField(
            model_name='fin_creditnote',
            name='price_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Finsys_App.fin_price_list'),
        ),
        migrations.AddField(
            model_name='fin_creditnote',
            name='price_list_applied',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employee_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 17)),
        ),
        migrations.AlterField(
            model_name='fin_attendance_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 17)),
        ),
        migrations.AlterField(
            model_name='fin_attendance_history',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 17)),
        ),
        migrations.AlterField(
            model_name='fin_creditnote_history',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='holiday_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 17)),
        ),
    ]
