# Generated by Django 4.2.3 on 2024-02-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0009_remove_fin_sales_order_items_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fin_sales_order',
            name='file',
            field=models.FileField(default=None, null=True, upload_to='sales_order'),
        ),
    ]
