# Generated by Django 4.2.3 on 2024-01-16 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0009_fin_customers_fin_customers_history_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fin_Company_Payment_Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(max_length=100, null=True)),
                ('days', models.IntegerField(default=0, null=True)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
            ],
        ),
    ]
