# Generated by Django 4.2.3 on 2024-01-17 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0010_fin_company_payment_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fin_customers',
            name='payment_terms',
        ),
    ]
