# Generated by Django 4.2.3 on 2024-04-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0010_remove_fin_creditnote_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fin_creditnote',
            name='payment_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
