# Generated by Django 4.2.3 on 2024-02-05 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0011_fin_recurring_invoice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fin_recurring_invoice',
            old_name='Entry_Type',
            new_name='Entity_Type',
        ),
        migrations.CreateModel(
            name='Fin_Recurring_invoice_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn', models.CharField(max_length=100)),
                ('qty', models.IntegerField(default=0, null=True)),
                ('price', models.CharField(max_length=100)),
                ('tax', models.CharField(max_length=100)),
                ('discount', models.IntegerField(default=0, null=True)),
                ('total', models.IntegerField(default=0, null=True)),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('items', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_items')),
                ('recinvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_recurring_invoice')),
            ],
        ),
    ]
