# Generated by Django 4.2.3 on 2024-01-17 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0011_remove_fin_customers_payment_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_customers',
            name='payment_terms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_payment_terms'),
        ),
    ]
