# Generated by Django 4.2.3 on 2024-04-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0011_alter_fin_creditnote_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fin_creditnote',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fin_creditnote',
            name='invoice_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
