# Generated by Django 4.2.3 on 2024-02-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0013_fin_estimate_fin_estimate_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_estimate',
            name='bank_acc_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fin_estimate',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fin_estimate',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fin_estimate',
            name='upi_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
