# Generated by Django 4.2.3 on 2024-01-18 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0013_fin_cnotification_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fin_customers',
            name='payment_terms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Finsys_App.fin_company_payment_terms'),
        ),
        migrations.AlterField(
            model_name='fin_customers',
            name='price_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Finsys_App.fin_price_list'),
        ),
    ]
