# Generated by Django 4.2.3 on 2024-02-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0015_rename_exp_ship_date_fin_estimate_exp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_estimate',
            name='balance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
