# Generated by Django 4.2.3 on 2024-02-17 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0017_fin_purchase_bill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fin_Manual_Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.IntegerField(blank=True, null=True)),
                ('journal_no', models.CharField(max_length=100)),
                ('journal_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, default='INR-Indian Rupee', max_length=255, null=True)),
                ('subtotal_debit', models.FloatField(blank=True, default=0.0, null=True)),
                ('subtotal_credit', models.FloatField(blank=True, default=0.0, null=True)),
                ('total_debit', models.FloatField(blank=True, default=0.0, null=True)),
                ('total_credit', models.FloatField(blank=True, default=0.0, null=True)),
                ('balance_debit', models.FloatField(blank=True, default=0.0, null=True)),
                ('balance_credit', models.FloatField(blank=True, default=0.0, null=True)),
                ('file', models.FileField(default=None, null=True, upload_to='Journals')),
                ('status', models.CharField(default='Draft', max_length=150)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('LoginDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
            ],
        ),
        migrations.RenameField(
            model_name='fin_recurring_invoice',
            old_name='enddate',
            new_name='billdate',
        ),
        migrations.RenameField(
            model_name='fin_recurring_invoice',
            old_name='startdate',
            new_name='duedate',
        ),
        migrations.AlterField(
            model_name='fin_recurring_invoice',
            name='Adjustment',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='fin_recurring_invoice',
            name='CGST',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='fin_recurring_invoice',
            name='Grand_Total',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='fin_recurring_invoice',
            name='IGST',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='fin_recurring_invoice',
            name='Price_list',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='fin_recurring_invoice',
            name='Reference_Number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fin_recurring_invoice',
            name='SGST',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='fin_recurring_invoice',
            name='Shipping_charge',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='fin_recurring_invoice',
            name='Sub_Total',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='fin_recurring_invoice',
            name='Tax_Amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.CreateModel(
            name='Fin_Manual_Journal_Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.BigIntegerField()),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('LoginDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
            ],
        ),
        migrations.CreateModel(
            name='Fin_Manual_Journal_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('action', models.CharField(blank=True, choices=[('Created', 'Created'), ('Edited', 'Edited')], max_length=20, null=True)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('Journal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_manual_journal')),
                ('LoginDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
            ],
        ),
        migrations.CreateModel(
            name='Fin_Manual_Journal_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('Journal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_manual_journal')),
            ],
        ),
        migrations.CreateModel(
            name='Fin_Manual_Journal_Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('debit', models.FloatField(blank=True, default=0.0, null=True)),
                ('credit', models.FloatField(blank=True, default=0.0, null=True)),
                ('Account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Finsys_App.fin_chart_of_account')),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('Journal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_manual_journal')),
                ('LoginDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
            ],
        ),
    ]
