# Generated by Django 4.2.3 on 2024-03-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0024_fin_banking_bank_status_alter_employee_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fin_purchase_bill',
            name='porder_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
