# Generated by Django 4.2.3 on 2024-03-05 06:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0025_alter_fin_purchase_bill_porder_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fin_Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.IntegerField(blank=True, null=True)),
                ('expense_no', models.CharField(max_length=100)),
                ('expense_date', models.DateField(blank=True, null=True)),
                ('expense_account', models.CharField(blank=True, max_length=150, null=True)),
                ('expense_type', models.CharField(blank=True, max_length=150, null=True)),
                ('hsn_number', models.CharField(blank=True, max_length=50, null=True)),
                ('sac_number', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('tax_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('cheque_no', models.CharField(blank=True, max_length=100, null=True)),
                ('upi_no', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_acc_no', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('vendor_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('vendor_address', models.TextField(blank=True, null=True)),
                ('vendor_gst_type', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_gstin', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_source_of_supply', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('customer_address', models.TextField(blank=True, null=True)),
                ('customer_gst_type', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_gstin', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_place_of_supply', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('file', models.FileField(default=None, null=True, upload_to='expense')),
                ('status', models.CharField(default='Draft', max_length=150)),
                ('Account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Finsys_App.fin_chart_of_account')),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('Customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_customers')),
                ('LoginDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
                ('Vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_vendors')),
            ],
        ),
        migrations.AlterField(
            model_name='employee_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 5)),
        ),
        migrations.CreateModel(
            name='Fin_Expense_Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.BigIntegerField()),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('LoginDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
            ],
        ),
        migrations.CreateModel(
            name='Fin_Expense_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('action', models.CharField(blank=True, choices=[('Created', 'Created'), ('Edited', 'Edited')], max_length=20, null=True)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('Expense', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_expense')),
                ('LoginDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
            ],
        ),
        migrations.CreateModel(
            name='Fin_Expense_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('Expense', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_expense')),
            ],
        ),
    ]
